name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run cypress 
        uses: cypress-io/github-action@v2
        with:
         start: npm start
         env: grepTags=@bpTest
