name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

      
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2  
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
