name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run cypress 
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Start the server
        run: npm start &

      - name: Run Mono tests
        if: ${{ github.event.inputs.mono == 'true' }}
        uses: cypress-io/github-action@v2
        with:
          install: false
          env: grepTags=@bpTest

      - name: Run Container tests
        if: ${{ github.event.inputs.container == 'true' }}
        uses: cypress-io/github-action@v2
        with:
          install: false
          env: grepTags=@bpcTest
